[package]
name = "eclipsis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy_obj = "0.6.0"
rand = "0.8.5"
heron = { version = "2.0.1", features = ["3d"] }